#unit = Sum;

#Sum = Sum "+" Product | Sum "-" Product | Product;
#Product = Product "*" Factor | Product "/" Factor | Factor;
#Factor = "(" Sum ")" | <num>;

unit = expr;

expr = <num>
     || :right "-" expr
     || :left expr "*" expr
      | :left expr "/" expr
     || :left expr "+" expr
      | :left expr "-" expr
     || :right expr "=" expr;
